# Clear out our raw table.
#truncate table raw;

# Load Program. You'll need to run this for each file.
set @SourceFile = 'D:\\Raw Data\\Authority\\authority2009.part00';

load data local infile
	'D:\\Raw Data\\Authority\\authority2009.part00' ignore
into table
	raw
character set latin1
fields terminated by '\t'
optionally enclosed by '"'
escaped by ''
lines terminated by '\n'
(
	@Blocks,
	@Probabilities,
	@Cluster,
	@AuthorID,
	@ClusterSize,
	@NameVariants,
	@LastNameVariants,
	@FirstNameVariants,
	@MiddleInitialVariants,
	@SuffixVariants,
	@Emails,
	@YearRange,
	@Affiliations,
	@MeSHTerms,
	@Journals,
	@TitleWords,
	@CoauthorNames,
	@CoauthorIDs,
	@AuthorNameInstances,
	@GrantIDs,
	@TotalTimesCited,
	@HIndex,
	@CitationCounts,
	@Cited,
	@CitedBy,
	@AuthorID_10Year,
	@ClusterSize_10Year,
	@NameVariants_10Year,
	@LastNameVariants_10Year,
	@FirstNameVariants_10Year,
	@MiddleInitialVariants_10Year,
	@SuffixVariants_10Year,
	@Emails_10Year,
	@YearRange_10Year,
	@Affiliations_10Year,
	@MeSHTerms_10Year,
	@Journals_10Year,
	@TitleWords_10Year,
	@CoauthorNames_10Year,
	@CoauthorIDs_10Year,
	@AuthorNameInstances_10Year,
	@GrantIDs_10Year,
	@TotalTimesCited_10Year,
	@HIndex_10Year,
	@CitationCounts_10Year,
	@Cited_10Year,
	@CitedBy_10Year
)
set
	SourceFile = @SourceFile,
	Blocks = nullif(@Blocks, ''),
	Probabilities = nullif(@Probabilities, ''),
	Cluster = nullif(@Cluster, ''),
	AuthorID = nullif(@AuthorID, ''),
	ClusterSize = cast(nullif(@ClusterSize, '') as unsigned integer),
	NameVariants = nullif(@NameVariants, ''),
	LastNameVariants = nullif(@LastNameVariants, ''),
	FirstNameVariants = nullif(@FirstNameVariants, ''),
	MiddleInitialVariants = nullif(@MiddleInitialVariants, ''),
	SuffixVariants = nullif(@SuffixVariants, ''),
	Emails = nullif(@Emails, ''),
	YearRange = nullif(@YearRange, ''),
	Affiliations = nullif(@Affiliations, ''),
	MeSHTerms = nullif(@MeSHTerms, ''),
	Journals = nullif(@Journals, ''),
	TitleWords = nullif(@TitleWords, ''),
	CoauthorNames = nullif(@CoauthorNames, ''),
	CoauthorIDs = nullif(@CoauthorIDs, ''),
	AuthorNameInstances = nullif(@AuthorNameInstances, ''),
	GrantIDs = nullif(@GrantIDs, ''),
	TotalTimesCited = cast(nullif(@TotalTimesCited, '') as unsigned int),
	HIndex = cast(nullif(@HIndex, '') as decimal),
	CitationCounts = nullif(@CitationCounts, ''),
	Cited = nullif(@Cited, ''),
	CitedBy = nullif(@CitedBy, ''),
	AuthorID_10Year = nullif(@AuthorID_10Year, ''),
	ClusterSize_10Year = cast(nullif(@ClusterSize_10Year, '') as unsigned int),
	NameVariants_10Year = nullif(@NameVariants_10Year, ''),
	LastNameVariants_10Year = nullif(@LastNameVariants_10Year, ''),
	FirstNameVariants_10Year = nullif(@FirstNameVariants_10Year, ''),
	MiddleInitialVariants_10Year = nullif(@MiddleInitialVariants_10Year, ''),
	SuffixVariants_10Year = nullif(@SuffixVariants_10Year, ''),
	Emails_10Year = nullif(@Emails_10Year, ''),
	YearRange_10Year = nullif(@YearRange_10Year, ''),
	Affiliations_10Year = nullif(@Affiliations_10Year, ''),
	MeSHTerms_10Year = nullif(@MeSHTerms_10Year, ''),
	Journals_10Year = nullif(@Journals_10Year, ''),
	TitleWords_10Year = nullif(@TitleWords_10Year, ''),
	CoauthorNames_10Year = nullif(@CoauthorNames_10Year, ''),
	CoauthorIDs_10Year = nullif(@CoauthorIDs_10Year, ''),
	AuthorNameInstances_10Year = nullif(@AuthorNameInstances_10Year, ''),
	GrantIDs_10Year = nullif(@GrantIDs_10Year, ''),
	TotalTimesCited_10Year = cast(nullif(@TotalTimesCited_10Year, '') as unsigned int),
	HIndex_10Year = cast(nullif(@HIndex_10Year, '') as decimal),
	CitationCounts_10Year = nullif(@CitationCounts_10Year, ''),
	Cited_10Year = nullif(@Cited_10Year, ''),
	CitedBy_10Year = nullif(@CitedBy_10Year, '')