CREATE TABLE IF NOT EXISTS program (
	CFDAProgramId int not null auto_increment,
	ProgramTitle varchar(500) default null,
	ProgramNumber char(6) default null,
	PopularName varchar(1000) default null,
	FederalAgency varchar(500) default null,
	Authorization text default null,
	Objectives text default null,
	TypesOfAssistance text default null,
	UsesAndUseRestrictions text default null,
	ApplicantEligibility text default null,
	BeneficiaryEligibility text default null,
	CredentialsDocumentation text default null,
	PreapplicationCoordination text default null,
	ApplicationProcedures text default null,
	AwardProcedure text default null,
	Deadlines text default null,
	RangeOfApprovalDisapprovalTime text default null,
	Appeals text default null,
	Renewals text default null,
	FormulaAndMatchingRequirements text default null,
	LengthAndTimePhasingOfAssistance text default null,
	Reports text default null,
	Audits text default null,
	Records text default null,
	AccountIdentification text default null,
	Obligations text default null,
	RangeAndAverageOfFinancialAssistance text default null,
	ProgramAccomplishments text default null,
	RegulationsGuidelinesAndLiterature text default null,
	RegionalOrLocalOffice text default null,
	HeadquartersOffice text default null,
	WebsiteAddress varchar(500) default null,
	RelatedPrograms text default null,
	ExamplesOfFundedProjects mediumtext default null,
	CriteriaForSelectingProposals text default null,
	PublishedDate date default null,
	ParentShortname varchar(20) default null,
	URL varchar(100) default null,
	Recovery char(3) default null,
	UMSourceFile varchar(100) default null,
	primary key (CFDAProgramId)
	) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Raw data from CFDA FTP site';
	