CREATE TABLE `author` (
	`RawID` INT(11) NOT NULL AUTO_INCREMENT,
	`Cluster` VARCHAR(50) NULL DEFAULT NULL,
	`AuthorID` VARCHAR(100) NULL DEFAULT NULL,
	`ClusterSize` INT(10) UNSIGNED NULL DEFAULT NULL,
	`YearRange` VARCHAR(50) NULL DEFAULT NULL,
	`TotalTimesCited` INT(10) UNSIGNED NULL DEFAULT NULL,
	`HIndex` FLOAT UNSIGNED NULL DEFAULT NULL,
	`AuthorID_10Recent` VARCHAR(50) NULL DEFAULT NULL,
	`ClusterSize_10Recent` INT(10) UNSIGNED NULL DEFAULT NULL,
	`YearRange_10Recent` VARCHAR(50) NULL DEFAULT NULL,
	`TotalTimesCited_10Recent` INT(10) UNSIGNED NULL DEFAULT NULL,
	`HIndex_10Recent` FLOAT UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`RawID`),
	UNIQUE INDEX `RawID` (`RawID`),
	UNIQUE INDEX `AuthorID` (`AuthorID`),
	UNIQUE INDEX `AuthorID_10Recent` (`AuthorID_10Recent`)
)
COMMENT='Raw data from Authority files from Torvik'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=10282923;
