CREATE TABLE `block` (
	`BlockId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawId` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`Name` VARCHAR(100) NOT NULL,
	`PositionInBlock` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`BlockId`),
	UNIQUE INDEX `BlockId` (`BlockId`),
	INDEX `RawId` (`RawId`)
)
ENGINE=InnoDB;
