CREATE TABLE `citationcount10recent` (
	`CitationCount10RecentID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawID` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`PMID` INT(11) UNSIGNED NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`CitationCount10RecentID`),
	UNIQUE INDEX `CitationCount10RecentID` (`CitationCount10RecentID`),
	INDEX `RawID` (`RawID`)
)
ENGINE=InnoDB;
