CREATE TABLE `citedby` (
	`CitedById` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawId` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`PMID` INT(11) UNSIGNED NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`CitedById`),
	UNIQUE INDEX `CitedById` (`CitedById`),
	INDEX `RawId` (`RawId`)
)
ENGINE=InnoDB;
