CREATE TABLE `cited` (
	`CitedID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawID` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`PMID` INT(11) UNSIGNED NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`CitedID`),
	UNIQUE INDEX `CitedID` (`CitedID`),
	INDEX `RawID` (`RawID`)
)
ENGINE=InnoDB;
