CREATE TABLE `cited10recent` (
	`Cited10RecentId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawId` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`PMID` INT(11) UNSIGNED NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`Cited10RecentId`),
	UNIQUE INDEX `Cited10RecentId` (`Cited10RecentId`),
	INDEX `RawId` (`RawId`)
)
ENGINE=InnoDB;
