CREATE TABLE `cited10recent` (
	`Cited10RecentID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawID` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`PMID` INT(11) UNSIGNED NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`Cited10RecentID`),
	UNIQUE INDEX `Cited10RecentID` (`Cited10RecentID`),
	INDEX `RawID` (`RawID`)
)
ENGINE=InnoDB;
