CREATE TABLE `citedby10recent` (
	`CitedBy10RecentId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawId` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`PMID` INT(11) UNSIGNED NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`CitedBy10RecentId`),
	UNIQUE INDEX `CitedBy10RecentId` (`CitedBy10RecentId`),
	INDEX `RawId` (`RawId`)
)
ENGINE=InnoDB;
