CREATE TABLE `cited` (
	`CitedId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawId` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`PMID` INT(11) UNSIGNED NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`CitedId`),
	UNIQUE INDEX `CitedId` (`CitedId`),
	INDEX `RawId` (`RawId`)
)
ENGINE=InnoDB;
