CREATE TABLE `citedby` (
	`CitedByID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawID` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`PMID` INT(11) UNSIGNED NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`CitedByID`),
	UNIQUE INDEX `CitedByID` (`CitedByID`),
	INDEX `RawID` (`RawID`)
)
ENGINE=InnoDB;
