CREATE TABLE `citedby10recent` (
	`CitedBy10RecentID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawID` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`PMID` INT(11) UNSIGNED NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`CitedBy10RecentID`),
	UNIQUE INDEX `CitedBy10RecentID` (`CitedBy10RecentID`),
	INDEX `RawID` (`RawID`)
)
ENGINE=InnoDB;
