CREATE TABLE `coauthorid` (
	`CoauthorIDID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawID` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`Name` VARCHAR(100) NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`CoauthorIDID`),
	UNIQUE INDEX `CoauthorIDID` (`CoauthorIDID`),
	INDEX `RawID` (`RawID`)
)
ENGINE=InnoDB;
