CREATE TABLE `grantid` (
	`GrantIdId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawId` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`Name` VARCHAR(50) NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`GrantIdId`),
	UNIQUE INDEX `GrantIdId` (`GrantIdId`),
	INDEX `RawId` (`RawId`)
)
ENGINE=InnoDB;
