CREATE TABLE `grantid10recent` (
	`GrantId10RecentId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawId` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`Name` VARCHAR(50) NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`GrantId10RecentId`),
	UNIQUE INDEX `GrantId10RecentId` (`GrantId10RecentId`),
	INDEX `RawId` (`RawId`)
)
ENGINE=InnoDB;
