CREATE TABLE `journal10recent` (
	`Journal10recentID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawID` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`Name` VARCHAR(100) NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`Journal10recentID`),
	UNIQUE INDEX `Journal10recentID` (`Journal10recentID`),
	INDEX `RawID` (`RawID`)
)
ENGINE=InnoDB;
