CREATE TABLE `journal10recent` (
	`Journal10RecentId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawId` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`Name` VARCHAR(100) NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`Journal10RecentId`),
	UNIQUE INDEX `Journal10RecentId` (`Journal10RecentId`),
	INDEX `RawId` (`RawId`)
)
ENGINE=InnoDB;
