CREATE TABLE `meshterm` (
	`MeshTermID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawID` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`Name` VARCHAR(200) NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`MeshTermID`),
	UNIQUE INDEX `MeshTermID` (`MeshTermID`),
	INDEX `RawID` (`RawID`)
)
ENGINE=InnoDB;
