CREATE TABLE `meshterm10recent` (
	`MeshTerm10RecentID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawID` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`Name` VARCHAR(200) NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`MeshTerm10RecentID`),
	UNIQUE INDEX `MeshTerm10RecentID` (`MeshTerm10RecentID`),
	INDEX `RawID` (`RawID`)
)
ENGINE=InnoDB;
