CREATE TABLE `meshterm10recent` (
	`MeshTerm10RecentId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawId` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`Name` VARCHAR(200) NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`MeshTerm10RecentId`),
	UNIQUE INDEX `MeshTerm10RecentId` (`MeshTerm10RecentId`),
	INDEX `RawId` (`RawId`)
)
ENGINE=InnoDB;
