CREATE TABLE `titleword` (
	`TitleWordId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawId` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`Name` VARCHAR(100) NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`TitleWordId`),
	UNIQUE INDEX `TitleWordId` (`TitleWordId`),
	INDEX `RawId` (`RawId`)
)
ENGINE=InnoDB;
