CREATE TABLE `titleword` (
	`TitleWordID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`RawID` INT(11) UNSIGNED NOT NULL,
	`Position` INT(11) UNSIGNED NOT NULL,
	`Name` VARCHAR(100) NOT NULL,
	`Count` INT(11) UNSIGNED NOT NULL,
	PRIMARY KEY (`TitleWordID`),
	UNIQUE INDEX `TitleWordID` (`TitleWordID`),
	INDEX `RawID` (`RawID`)
)
ENGINE=InnoDB;
