#select count(*) from ResearchGovRaw -- 87,531
select max(char_length(Awardee)) from ResearchGovRaw; -- 255
select max(char_length(DoingBusinessAsName)) from ResearchGovRaw; -- 255
select max(char_length(PDPIName)) from ResearchGovRaw; -- 40
select max(char_length(PDPIPhone)) from ResearchGovRaw; -- 14
select max(char_length(PDPIEmail)) from ResearchGovRaw; -- 42
select max(char_length(CoPDsCoPIs)) from ResearchGovRaw; -- 124
select max(char_length(AwardDate)) from ResearchGovRaw; -- 13
select max(char_length(EstimatedTotalAwardAmount)) from ResearchGovRaw; -- 15
select max(char_length(FundsObligatedToDate)) from ResearchGovRaw; -- 15
select max(char_length(AwardStartDate)) from ResearchGovRaw; -- 13
select max(char_length(AwardExpirationDate)) from ResearchGovRaw; -- 13
select max(char_length(TransactionType)) from ResearchGovRaw; -- 22
select max(char_length(Agency)) from ResearchGovRaw; -- 4
select max(char_length(AwardingAgencyCode)) from ResearchGovRaw; -- 7
select max(char_length(FundingAgencyCode)) from ResearchGovRaw; -- 7
select max(char_length(CFDANumber)) from ResearchGovRaw; -- 9
select max(char_length(PrimaryProgramSource)) from ResearchGovRaw; -- 37
select max(char_length(AwardTitleOrDescription)) from ResearchGovRaw; -- 255
select max(char_length(FederalAwardIDNumber)) from ResearchGovRaw; -- 17
select max(char_length(DUNSID)) from ResearchGovRaw; -- 16
select max(char_length(ParentDUNSID)) from ResearchGovRaw; -- 12
select max(char_length(Program)) from ResearchGovRaw; -- 30
select max(char_length(ProgramOfficerName)) from ResearchGovRaw; -- 31
select max(char_length(ProgramOfficerPhone)) from ResearchGovRaw; -- 14
select max(char_length(ProgramOfficerEmail)) from ResearchGovRaw; -- 16
select max(char_length(AwardeeStreet)) from ResearchGovRaw; -- 32
select max(char_length(AwardeeCity)) from ResearchGovRaw; -- 26
select max(char_length(AwardeeState)) from ResearchGovRaw; -- 2
select max(char_length(AwardeeZIP)) from ResearchGovRaw; -- 10
select max(char_length(AwardeeCounty)) from ResearchGovRaw; -- 22
select max(char_length(AwardeeCountry)) from ResearchGovRaw; -- 4
select max(char_length(AwardeeCongressionalDistrict)) from ResearchGovRaw; -- 5
select max(char_length(PrimaryOrganizationName)) from ResearchGovRaw; -- 64
select max(char_length(PrimaryStreet)) from ResearchGovRaw; -- 73
select max(char_length(PrimaryCity)) from ResearchGovRaw; -- 26
select max(char_length(PrimaryState)) from ResearchGovRaw; -- 2
select max(char_length(PrimaryZIP)) from ResearchGovRaw; -- 10
select max(char_length(PrimaryCounty)) from ResearchGovRaw; -- 22
select max(char_length(PrimaryCountry)) from ResearchGovRaw; -- 4
select max(char_length(PrimaryCongressionalDistrict)) from ResearchGovRaw; -- 5
select max(char_length(AbstractAtTimeOfAward)) from ResearchGovRaw; -- 7999
select max(char_length(PublicationsProducedAsAResultsOfThisResearch)) from ResearchGovRaw; -- 32557
select max(char_length(PublicationsProducedAsConferenceProceedings)) from ResearchGovRaw; -- 32557
select max(char_length(ProjectOutcomesReport)) from ResearchGovRaw; -- 20079
